Models/City.cs
namespace ResursGAP.Models
{
    public class City
    {
        public int CityId { get; set; }
        public string Name { get; set; }
        public decimal ZonePrice { get; set; }
    }
}

Controllers/CityController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ResursGAP.Models;

namespace ResursGAP.Controllers
{
    public class CityController : Controller
    {
        private readonly AppDbContext _context;
        public CityController(AppDbContext context)
        {
            _context = context;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            var cities = _context.Cities.ToList();

            if (cities == null || cities.Count == 0)
            {
                
                return NotFound();
            }
            var cityViewModels = cities.Select(c => new City
            {
                CityId = c.CityId,
                Name = c.Name,
                ZonePrice = c.ZonePrice
            }).ToList();

            
            return View(cityViewModels);
        }


       
        public ActionResult Details(int id)
        {
            
            var city = _context.Cities.Find(id);

            
            if (city == null)
            {
                return NotFound(); 
            }

            
            return View(city);
        }
    }
    
}

Views/City/Details.cshtml
@model ResursGAP.Models.City

<h2>Подробности о городе</h2>

<p>Название города: @Model.Name</p>
<p>Зональная цена: @Model.ZonePrice</p>
    <td>
        
    <p><a href="@Url.Action("Index", "City")" class="btn btn-secondary btn-hover-blue">Назад к списку</a></p>
    </td>

Views/City/Index.cshtml
@model IEnumerable<ResursGAP.Models.City>

<table class="table table-striped">
    <thead>
        <tr>
            
            <th>Город </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                
                <td>
                    <a asp-action="Details" asp-route-id="@item.CityId" class="btn btn-hover-blue">Подробности</a>
                </td>
            </tr>
        }
    </tbody>
</table>