Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ResursGAP.Models
{
    public class Order
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int OrderId { get; set; }

        [Required(ErrorMessage = "Город отправителя обязателен")]
        public string SenderCity { get; set; }

        [Required(ErrorMessage = "Адрес отправителя обязателен")]
        [StringLength(100, ErrorMessage = "Адрес отправителя должен содержать не более 100 символов")]
        public string SenderAddress { get; set; }

        [Required(ErrorMessage = "Город получателя обязателен")]
        public string ReceiverCity { get; set; }

        [Required(ErrorMessage = "Город получателя обязателен")]
        [StringLength(100, ErrorMessage = "Адрес получателя должен содержать не более 100 символов")]
        public string ReceiverAddress { get; set; }

        [Required(ErrorMessage = "Введите вес груза")]
        public double Weight { get; set; }

        [Required(ErrorMessage = "Выберите дату")]
        public DateTime DeliveryDate { get; set; }

        public decimal DeliveryCost { get; set; }

        // Связь с фурой
        [ForeignKey("Truck")]
        public int? TruckId { get; set; }
        public Truck? Truck { get; set; }

        //Связь с маршрутами
        //public ICollection<Route> Routes { get; set; }

       
    }
}

Models/RouteDetailsViewModel.cs
namespace ResursGAP.Models
{
    public class RouteDetailsViewModel
    {
        public Truck Truck { get; set; }
        public List<Order> Orders { get; set; }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ResursGAP.Models;
using ResursGAP.Service;
using Route = ResursGAP.Models.Route;

namespace ResursGAP.Controllers
{
    public class OrderController : Controller
    {
        private readonly DeliveryService _deliveryService;
        private readonly AppDbContext _dbContext;
        private readonly DistributeOrdersToTruckService _distributeService;
        public OrderController(AppDbContext dbContext, DeliveryService deliveryService, DistributeOrdersToTruckService distributeService)
        {
            _dbContext = dbContext;
            _deliveryService = deliveryService;
            _distributeService = distributeService;
        }
        // GET: OrderController
        public ActionResult Index()
        {
            
         var orders = _dbContext.Orders
          .Include(o => o.Truck) // Включить связанный объект Truck
          .ToList();

            if (orders == null)
            {

                return NotFound();
            }
            var ordersViewModels = orders.Select(c => new Order
            {
                OrderId = c.OrderId,
                SenderCity = c.SenderCity,
                ReceiverCity = c.ReceiverCity
            }).ToList();


            return View(ordersViewModels);

            
        }

        // Выбор машины на по массе груза
        public IActionResult GetAvailableTrucks(double weight)
        {
            // Запросите доступные грузовики из базы данных на основе массы груза
            var Trucks = _dbContext.Trucks.Where(t => t.WeightInTons >= weight).ToList();

            // Отправьте список доступных грузовиков в частичное представление
            return PartialView("_PartialTruck", Trucks);
        }

        public ActionResult Details(int id)
        {
            var order = _dbContext.Orders.Find(id);

          
            if (order == null)
            {
                return NotFound(); 
            }

            
            return View(order);
        }

        // GET: OrderController/Create
        public ActionResult Create()
        {
            
            List<City> cities = _dbContext.Cities.ToList();
         

            List<SelectListItem> cityList = cities.Select(city => new SelectListItem
            {
                Text = city.Name
            }).ToList();
           
            ViewBag.CityList = cityList;

           

            return View();
        }

       
        // POST: OrderController/Create
        [HttpPost]
       
        public IActionResult Create(Order order)
        {
           
            decimal deliveryCost = _deliveryService.CalculateDeliveryCost(order.SenderCity, order.ReceiverCity);
            order.DeliveryCost = deliveryCost;
            double weight = order.Weight;

            decimal newDeliveryCost = deliveryCost * (decimal)order.Weight; 
            order.DeliveryCost = newDeliveryCost;
           
            // Найдите подходящий грузовик на основе массы груза
            Truck selectedTruck = _dbContext.Trucks.FirstOrDefault(truck => truck.WeightInTons >= weight && truck.LoadedWeightInTons + weight <= truck.WeightInTons);

            

            if (selectedTruck != null)
            {
                // Если найден подходящий грузовик, установите TruckId
                order.TruckId = selectedTruck.TruckId;
                selectedTruck.LoadedWeightInTons += weight;
                _dbContext.SaveChanges();
            }
            else
            {
             
               
               ModelState.AddModelError(string.Empty, "Нет подходящего грузовика для указанной массы груза.");
                return View(order);
            }

            if (ModelState.IsValid)
            {
                
                _dbContext.Orders.Add(order);
                 _dbContext.SaveChanges();

                return RedirectToAction("Index");
              

            }
           

            return RedirectToAction("Create");
            
        }

       public IActionResult RouteDetails(int truckId)
        {
            // Получить все заказы, связанные с определенной машиной (truckId)
            var ordersForTruck = _dbContext.Orders
                .Where(o => o.TruckId == truckId)
                .ToList();

            
            if (ordersForTruck.Count == 0)
            {
                ViewBag.Message = "Нет данных о заказах для этой машины.";
                return View();
            }

            // Загрузить информацию о машине 
            var truck = _dbContext.Trucks.FirstOrDefault(t => t.TruckId == truckId);

            if (truck == null)
            {
                
                return NotFound();
            }

            // Модель представления  ViewModel, которая  содержит информацию о машине и связанных заказах
            var viewModel = new RouteDetailsViewModel
            {
                Truck = truck,
                Orders = ordersForTruck
            };

            return View(viewModel);
        }

        [HttpGet]
      
        public IActionResult Delete(int orderId)
        {
            
            var order = _dbContext.Orders.FirstOrDefault(o => o.OrderId == orderId);
          
            
            if (order == null)
            {
                return NotFound();
            }

            var truck = _dbContext.Trucks.FirstOrDefault(t => t.TruckId == order.TruckId);

            if (truck != null)
            {
                
                truck.LoadedWeightInTons = truck.LoadedWeightInTons-order.Weight;
            }

            // Удалите заказ из базы данных
            _dbContext.Orders.Remove(order);
           
            _dbContext.SaveChanges();

            
            return RedirectToAction("Index");
        }

    }
}

Views/Order/Create.cshtml
@model ResursGAP.Models.Order

<link rel="stylesheet" href="~/css/Order.css">
<script src="~/js/Order.js"></script>
<form asp-action="Create">
    <div class="form-group">
        <label asp-for="SenderCity">Город отправителя</label>
        <select asp-for="SenderCity" asp-items="ViewBag.CityList"></select>
        <span asp-validation-for="SenderCity" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SenderAddress">Адрес отправителя</label>
        <input asp-for="SenderAddress" class="form-control" />
        <span asp-validation-for="SenderAddress" class="text-danger"></span>
    </div>
    
      <div class="form-group">
        <label asp-for="ReceiverCity">Город получателя</label>
        <select asp-for="ReceiverCity" asp-items="ViewBag.CityList"></select>
        <span asp-validation-for="ReceiverCity" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ReceiverAddress">Адрес получателя</label>
        <input asp-for="ReceiverAddress" class="form-control" />
        <span asp-validation-for="ReceiverAddress" class="text-danger"></span>

    </div>

   <!-- <script>
        function getAvailableTrucks() {
            var weight = $("#Weight").val();

            $.ajax({
                url: "/Order/GetAvailableTrucks",
                type: "GET",
                data: { weight: weight },
                success: function (data) {
                    $("#availableTrucks").html(data);
                },
                error: function () {
                    alert("Произошла ошибка при загрузке доступных грузовиков.");
                }
            });
        }
     </script> -->

   
        
    <div class="form-group">
        <label asp-for="Weight">Масса груза</label>
        <!--<input asp-for="Weight" class="form-control" />-->
        <input asp-for="Weight" class="form-control" onchange="getAvailableTrucks()" />
        <span asp-validation-for="Weight" class="text-danger"></span>
    </div>

   

   <!-- <div id="availableTrucks">
        await Html.PartialAsync("_PartialTruck", new List<Truck>()) 
    </div>
    -->

 
  

    <div class="form-group">
        <label asp-for="DeliveryDate">Дата забора груза</label>
        <input asp-for="DeliveryDate" class="form-control" type="date" />
        <span asp-validation-for="DeliveryDate" class="text-danger"></span>

    </div>
    <div class="form-group">
        <input type="submit" value="Создать заказ" class="btn btn-primary" />
    </div>
   
</form>

Views/Order/Details.cshtml
@model ResursGAP.Models.Order

<h2>Подробности о Заказе</h2>

<p><span style="font-weight: bold;">Город отправления:</span><u> @Model.SenderCity</u></p>
<p> <span style="font-weight: bold;">Город прибытия:</span> <u>@Model.ReceiverCity</u></p>
<p><span style="font-weight: bold;">Адрес прибытия:</span> <u>@Model.ReceiverAddress</u></p>
<p><span style="font-weight: bold;">Масса груза:</span> <u>@Model.Weight тонн</u></p>
<p><span style="font-weight: bold;">Дата отправления:</span> <u>@Model.DeliveryDate.ToShortDateString()</u></p>
<p><span style="font-weight: bold;">Стоимость доставки:</span><u> @Model.DeliveryCost</u> рублей</p>


<td>
   <a asp-action="RouteDetails" asp-route-truckId="@Model.TruckId" class="btn btn-primary btn-hover-blue">Детали маршрута</a>
</td>

Views/Order/Index.cshtml
@model IEnumerable<ResursGAP.Models.Order>
<body>
<h2>Список заказов</h2>

    
    <script src="~/js/site.js" async></script>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Номер заказа</th>
            <th>Город отправителя</th>
            <th>Город получателя</th>
            
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.OrderId</td>
                <td>@item.SenderCity</td>
                <td>@item.ReceiverCity</td>
                
                <td>
                        <a asp-action="Details" asp-route-id="@item.OrderId" class="btn btn-hover-blue">Подробности</a>
                </td>
                <td>
                    <a asp-controller="Order" asp-action="Delete" asp-route-orderId="@item.OrderId" class="btn btn-danger" 
                    data-confirm="Вы уверены, что хотите удалить этот заказ?">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>
 </body>

Views/Order/RouteDetails.cshtml
@model ResursGAP.Models.RouteDetailsViewModel

<h2>Детали маршрута для машины @Model.Truck.Name</h2>

@if (ViewBag.Message != null)
{
    <p>@ViewBag.Message</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Номер заказа</th>
                <th>Город назначения</th>
                <th>Масса груза (тонны)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model.Orders)
            {
                <tr>
                    <td>@order.OrderId</td>
                    <td>@order.ReceiverCity</td>
                    <td>@order.Weight</td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Order/_PartialTruck.cshtml
@model List<Truck>

<label for="TruckId">Выберите грузовик:</label>
<select id="TruckSelect" class="form-control">
    <option value="">Выберите грузовик</option>
    @foreach (var truck in Model)
    {
        <option value="@truck.TruckId">@truck.Name</option>
    }
</select>